### ISSUE TITLE
Remove Connection invitation section in menu

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1264]
The "Connection invitation" and "Create a connection invitation" menu options are replaced by the "Scan my QR code" option. Please remove.

####Description of feature / user story####

####Acceptance Criteria####

####Wireframes or relevant image assets / links####

**Comment by wadeking98** [comment]
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/904

**Comment by knguyenBC** [comment]
@wadeking98 This is not resolved. Connection invitation option in the menu is still available. Checked in build 1087 for both iOS and Android.

**Comment by nodlesh** [comment]
I think we should move this back to Estimated Ready or Sprint Backlog. Which one? @hiteshgh

**Comment by hiteshgh** [comment]
moved to sprint backlog

**Comment by wadeking98** [comment]
PR committed, waiting for arrival in testflight

**Comment by knguyenBC** [comment]
Looks good. closing.
