### ISSUE TITLE
On mobile, after sending information after a proof request, vc-authn does not receive or provide feedback of the information sent

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#1997]
### Description of problem
When a person attempts to access a service page on a mobile device using BC Wallet, they are able to successfully open the wallet via deeplink, receive a proof request and send the info over, however when they return to the service page, vc-authn does not provide any change to the interface. The page still displays the button "BC Wallet" in a pressed state. 

**Troubleshoot attempts:**
- No change after waiting after 1 minute
- Did not fix after changing to LTE/mobile data
- Did not fix after uninstalling and reinstalling app
- Also does not work on test builds

### Expected behavior
When the person returns to the service page after sharing information, vc-authn should display the correct message (either accepted, declined, not accepted etc.) and direct people through to the service (if accepted).

### Steps to reproduce
- on mobile device, go to either [ACM](https://justice.gov.bc.ca/dars/pre-vc-auth/) or [Courthouse libraries](https://www.courthouselibrary.ca/how-we-can-help/remote-access-subscription-databases)
- access the service using BC wallet
- Accept the proof request
- return to service page

### Screenshots and/or log output

https://github.com/bcgov/bc-wallet-mobile/assets/68872187/6312bd94-1bec-4795-b57e-f30a37077bac

### Environment
- [X] Occurs on Android
- [X] Occurs on iOS

Build #: 1.0.16

Android Device Model: 

iOS Device Model: 

### Workaround
none. use desktop?

### Severity
- [x] High
- [ ] Medium
- [ ] Low

**Comment by loneil** [comment]
Note that in any situations when going back to the app the BC Wallet button will be disabled and a pending message displayed. This is not deployed past VC-AuthN **DEV** yet though (can be seen [here](https://a2a-dev.apps.silver.devops.gov.bc.ca/pre-vc-auth/)).
Though that change should not affect ability for the verified case to go through described here.

**Comment by loneil** [comment]
This behaviour is working for me correctly consistently in any case I can try so far. (Need to try on an iPhone, but have used iPad)

Cases I am testing:
- Go to a2a test https://a2a-test.apps.silver.devops.gov.bc.ca/pre-vc-auth/
- Log in with VC-AuthN and hit BC Wallet button
- Accept proof in BC Wallet app, repeatedly tested various navigation cases:
   - Wait in the App for the proof to complete, go home, navigate back to browser
      - Try multitask app navigation (iOS and Android)
      - Try iOS top left previous app link
      - Try Android back gestures
   - Immediately multitask back to browser without waiting
      - Sit on page until proof completes
   - Wait a long time in BC Wallet app, click around to other things
      - Eventually go back to browser
      - Proof has completed in the background and logged in DARS audio page is sitting there

Above successful cases are working for me consistently on following cases
- Pixel 6. Android 14 AP1A.240505.005
  - Chrome 125.0.6422.112
  - Firefox 126.0.1
  - Home WiFi
  - LTE
- iPad Air 4th. iPadOS 17.4.1. Home WiFi.
  - Safari
     - Request Mobile Site
     - Request Desktop Site
  - Chrome
     - Request Mobile Site
     - Request Desktop Site



Android recording

https://github.com/bcgov/bc-wallet-mobile/assets/17445138/1add6d17-508d-41a6-9211-67109a7673a8

iPad recording

https://github.com/bcgov/bc-wallet-mobile/assets/17445138/c4f21019-4d9b-4290-9481-b8ff51391701

**Comment by esune** [comment]
It appears that the issue is with websockets being severed once the browser goes to the background (switch to wallet) and never re-established when the focus is regained (wallet back to browser). The issue seems to be more prominent with iOS.

Aiming to resolve this in https://github.com/bcgov/vc-authn-oidc/issues/548

**Comment by loneil** [comment]
I believe this is fixed in the next version of VCAuthN (currently in Dev environment). Tested out with Clecio on his iPhone a while back and was unable to get any failures.

**Comment by knguyenBC** [comment]
I tested production credentials and Courthouse libraries. 
iOS (iPhone SE) did not work
Android (Pixel 8) worked
https://github.com/bcgov/vc-authn-oidc/issues/548 did not resolve the issue for iOS it seems.

**Comment by esune** [comment]
Unless I am missing something, I think what @loneil did in https://github.com/bcgov/vc-authn-oidc/issues/548 is all we could do on our end (i.e.: all that can be done in the webapp to ensure websockets reconnect). We may have to look more in-depth at how app switching in iOS works and whether this is something we could solve in the mobile app code (maybe there's a way of specifying an app should not freeze for the specified interaction with another app?) or it is an issue that needs to be solved/supported at the OS level.
