### ISSUE TITLE
BC Wallet stays in locked out state even after reinstalling the app

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#2407]
### Description of problem
The BC Wallet stays in locked out state even after reinstalling the app

### Expected behavior
Reinstalling the app should reset the PIN and therefore the locked out state

### Steps to reproduce
- Input the wrong PIN until lockout
- Uninstall the wallet
- Reinstall the wallet
- Continue with setup
- Close and return to the app
- App will be in locked out state

### Environment
- [ ] Occurs on Android
- [x] Occurs on iOS

Build #: 1.0.23

Android Device Model: 

iOS Device Model: 

### Severity
- [ ] High
- [x] Medium
- [ ] Low

**Comment by knguyenBC** [comment]
Was able to replicate

**Comment by knguyenBC** [comment]
This is fixed in bifold: https://github.com/openwallet-foundation/bifold-wallet/pull/1467. Needs to be pulled into BC Wallet.

**Comment by cvarjao** [comment]
In one event, the user had the font size very large, and because the screen content is not scrollable, she couldn't see and reach the "try again" button. The workaround is to reduce the font size so that the user can see the "try again" button

**Comment by jleach** [comment]
I can reproduce this. Using iOS 16.6.2. I though this might be related to iCloud keychain sync but I don't think so any more. I turned it off and still encounter the problem:

1. Install and setup the app (password is fine, no biometrics)
2. Get locked out for 60 seconds
3. Continue to be locked out for 10 minutes
4. Delete and re-install the app
5. Go through the setup process and then kill / restart the app

You should be presented with the lockout timer when you restart the app. I think the fix should be that when the password setup screen should reset all the "lockout" state.

**Comment by al-rosenthal** [comment]
I was able to reproduce this with the production version of the app (from the Apple Store) but I was unable to reproduce the issue locally or from test flight. I believe the contents of this commit are responsible for fixing this issue: https://github.com/openwallet-foundation/bifold-wallet/commit/5bb6ae478051b95b885ef09d08201f9e426a7b36

There is an associated PR cleaning up more of the state surrounding the lock out login: https://github.com/openwallet-foundation/bifold-wallet/pull/1624
